feat(@artusx/plugin-koa): use find-my-way to improve perf
artusjs/artusx pull request #4
Opened 2024-02-29 16:11 UTC by Yaxian

To benchmark in `main` branch, I disabled both `checkAuth` and `LimitRate` middlewares. Use `FACTOR` multiply `11` to gen multiple routes.

The `Requests/sec` result compare:

| FACTOR| @koa/router | find-my-way |
| -------- | ------- | -------- |
| 1 | 11633.29 | 14644.27 |
| 5 | 10474.16 | 12408.07 |
| 10 | 9823.64 | 13710.47 |
| 20 | 5909.84 | 9150.35 |
| 50 | 4001.26 | 3552.96 |
| 100 | 2554.90 | 5645.61 |
| 200 | 1343.33 | 9383.24 |
| 500 | 540.95 | 9198.66 |
| 1000 | 279.51 | 8927.13 |

`factor=5` details

@koa/router
```
Running 3s test @ http://localhost:7001/10/child/grandchild/%40
  8 threads and 50 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.51ms    1.65ms  27.54ms   88.32%
    Req/Sec     1.35k   639.23    10.32k    96.27%
  32471 requests in 3.10s, 8.98MB read
  Non-2xx or 3xx responses: 32471
Requests/sec:  10474.16
Transfer/sec:      2.90MB
```

find-my-way
```
Running 3s test @ http://localhost:7001/10/child/grandchild/%40
  8 threads and 50 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.92ms    1.43ms  23.40ms   89.97%
    Req/Sec     1.56k   315.52     1.98k    74.60%
  38523 requests in 3.10s, 8.82MB read
  Non-2xx or 3xx responses: 38523
Requests/sec:  12408.07
Transfer/sec:      2.84MB
```

2024-03-01 02:38 UTC, thonatos requested changes

2024-03-01 02:38 UTC, thonatos commented on packages/plugins/koa/src/koa/router.ts
> +  singleton() {
类那边已经声明过是单例了，这里好像可以简化一下

2024-03-01 02:38 UTC, thonatos commented on packages/plugins/koa/src/koa/router.ts
> +export type RouterInstance = Router.Instance<Router.HTTPVersion.V1>;
1. KoaRouter: types.ts 里要导出 router 类型 
2. KoaRouterClient: 这个名称，先保持兼容，之后再改（已经在用了）

2024-03-01 02:38 UTC, thonatos commented on packages/apps/artusx-koa/src/middleware/LimitRate.ts
> +    if (process.env.BENCH_FIND_MY_WAY || process.env.BENCH_KOA_ROUTER) {
可以新建一个 bench 的应用做测试，这样就不用侵入式加配置了

2024-03-01 02:51 UTC, thonatos commented on packages/plugins/koa/src/lifecycle.ts
> +      const executionPipeline = new Pipeline();
executionPipeline 每次都是新的，其他地方也用不到，放到 try catch 里？

2024-03-02 07:58 UTC, Yaxian commented on packages/plugins/koa/src/lifecycle.ts
> +      const executionPipeline = new Pipeline();
done

2024-03-02 07:58 UTC, Yaxian commented on packages/apps/artusx-koa/src/middleware/LimitRate.ts
> +    if (process.env.BENCH_FIND_MY_WAY || process.env.BENCH_KOA_ROUTER) {
done

2024-03-02 07:59 UTC, Yaxian commented on packages/plugins/koa/src/koa/router.ts
> +export type RouterInstance = Router.Instance<Router.HTTPVersion.V1>;
please review  the code~

2024-03-02 08:01 UTC, Yaxian commented on packages/plugins/koa/src/koa/router.ts
> +  singleton() {
I try, but a bit difficult.  Please review again.

BTW, I found one problem.
file `koa/application.ts`

```
export default xx
```

file `koa/router.ts`

```
export default xx
```

file `index.ts`

```
export * from  './koa/application'
export * from  './koa/router'
``

I think it will confuse `default` in `index.ts`

2024-03-05 03:44 UTC, thonatos requested changes

2024-03-05 03:44 UTC, thonatos commented on packages/apps/artusx-koa-bench/docker-compose.yaml
should be deleted.

2024-03-05 03:44 UTC, thonatos commented on packages/apps/artusx-koa-bench/src/controller/home.ts
> +  @MW([traceTime])
traceTime can be removed.

2024-03-05 03:44 UTC, thonatos commented on packages/apps/artusx-koa-bench/src/lifecycle.ts
should be removed.

2024-03-05 03:44 UTC, thonatos commented on packages/apps/artusx-koa-bench/src/middleware/traceTime.ts
should be removed.

2024-03-05 03:44 UTC, thonatos commented on packages/apps/artusx-koa-bench/src/util.ts
should be removed?

2024-03-05 15:53 UTC, Yaxian commented on packages/apps/artusx-koa-bench/src/util.ts
done

2024-03-05 15:53 UTC, Yaxian commented on packages/apps/artusx-koa-bench/src/lifecycle.ts
done

2024-03-05 15:53 UTC, Yaxian commented on packages/apps/artusx-koa-bench/src/controller/home.ts
> +  @MW([traceTime])
done

2024-03-05 15:54 UTC, Yaxian commented on packages/apps/artusx-koa-bench/docker-compose.yaml
done

2024-03-06 02:21 UTC, thonatos approved these changes

2024-03-06 02:22 UTC, merged